alter table packing_lists
  add column if not exists source_invoice_id uuid references invoices on delete set null,
  add column if not exists shipper_name text,
  add column if not exists shipper_pic text,
  add column if not exists shipper_address text,
  add column if not exists shipper_city text,
  add column if not exists shipper_country text,
  add column if not exists shipper_phone text,
  add column if not exists shipper_email text,
  add column if not exists receiver_name text,
  add column if not exists receiver_pic text,
  add column if not exists receiver_address text,
  add column if not exists receiver_city text,
  add column if not exists receiver_country text,
  add column if not exists receiver_phone text,
  add column if not exists receiver_email text,
  add column if not exists total_packages integer,
  add column if not exists total_quantity numeric default 0,
  add column if not exists total_net_weight numeric default 0,
  add column if not exists total_gross_weight numeric default 0,
  add column if not exists total_cbm numeric default 0;
